name: Deploy to Hostinger

on:
  push:
    branches:
      - main  # This is your production branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install --no-dev --prefer-dist --optimize-autoloader

      - name: Copy .env.production to .env
        run: cp .env.production .env

      - name: Deploy to Hostinger via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          ftp-server: ftps://your-ftp-server.com  # Replace with your FTP server
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./public_html  # Path to your local directory
          git-ftp-args: --insecure
          ftp-args: --insecure

      - name: Run storage link
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no your_ssh_user@your_hostinger_ip 'cd /path/to/your/project && php artisan storage:link'
